% plot electrode locations with labels

hdl.fig = figure('color', 'w');
hdl.ax = axes('nextplot', 'add');

hdl.markers = plot(...
    [e_loc.y], [e_loc.x], ...
    'lineStyle', 'none',...
    'marker', 'o',...
    'markerSize', 25,...
    'markerEdgeColor', [0.2, 0.2, 0.2],...
    'markerFaceColor', [0.9, 0.9, 0.9]);

% add labels
for n = 1 : length(e_loc)
    
    hdl.text(n) = text(e_loc(n).y, e_loc(n).x, ...
        char(e_loc(n).labels), ...
        'visible', 'on', ...
        'horizontalAlignment',  'center'        ,...
        'verticalAlignment',    'middle'        ,...
        'color',                'k'             ,...
        'fontSize',             8               );

end